{
  "formatVersion" : "1.1",
  "createdBy" : {
    "gradle" : {
      "version" : "7.2"
    }
  },
  "component" : {
    "group" : "com.github.Anuken",
    "module" : "Arc",
    "version" : "eae3c2dc59",
    "attributes" : {
      "org.gradle.status" : "release"
    }
  },
  "variants" : [ {
    "name" : "apiElements",
    "attributes" : {
      "org.gradle.category" : "library",
      "org.gradle.dependency.bundling" : "external",
      "org.gradle.jvm.version" : "8",
      "org.gradle.libraryelements" : "jar",
      "org.gradle.usage" : "java-api"
    },
    "files" : [ {
      "name" : "flabel-eae3c2dc59.jar",
      "url" : "flabel-eae3c2dc59.jar",
      "size" : 33333,
      "sha512" : "9209b832593adcc8a2bf284e15ca34726f5a77385c8dd7b95063733af4b51d2794a0def5a09e18e0abd5d8f6c0f3ca6791e5a4b3884a52478a87535ff309dddf",
      "sha256" : "0218ff32fd44f15a0cbbc219e132e1d768420fb0a3b3c5a8dfc0430098c39ef6",
      "sha1" : "dc8dc8310d314c11fef21430fea31a6a1bef8354",
      "md5" : "2521af2651c7a8b0eb15445d613e6837"
    } ]
  }, {
    "name" : "runtimeElements",
    "attributes" : {
      "org.gradle.category" : "library",
      "org.gradle.dependency.bundling" : "external",
      "org.gradle.jvm.version" : "8",
      "org.gradle.libraryelements" : "jar",
      "org.gradle.usage" : "java-runtime"
    },
    "files" : [ {
      "name" : "flabel-eae3c2dc59.jar",
      "url" : "flabel-eae3c2dc59.jar",
      "size" : 33333,
      "sha512" : "9209b832593adcc8a2bf284e15ca34726f5a77385c8dd7b95063733af4b51d2794a0def5a09e18e0abd5d8f6c0f3ca6791e5a4b3884a52478a87535ff309dddf",
      "sha256" : "0218ff32fd44f15a0cbbc219e132e1d768420fb0a3b3c5a8dfc0430098c39ef6",
      "sha1" : "dc8dc8310d314c11fef21430fea31a6a1bef8354",
      "md5" : "2521af2651c7a8b0eb15445d613e6837"
    } ]
  }, {
    "name" : "javadocElements",
    "attributes" : {
      "org.gradle.category" : "documentation",
      "org.gradle.dependency.bundling" : "external",
      "org.gradle.docstype" : "javadoc",
      "org.gradle.usage" : "java-runtime"
    },
    "files" : [ {
      "name" : "flabel-eae3c2dc59.jar",
      "url" : "flabel-eae3c2dc59.jar",
      "size" : 72942,
      "sha512" : "65eb6292679af13134ffad93a0bb76edaafb97a01bebec03eb1dc44540a5694688166147fb2988a66d9b7530b668c99bdf6277784eafecbb999820c4f9cea2f2",
      "sha256" : "7224cc731265d64deec8b71875056904e9f697279b3fe0290d7ade7eddefb245",
      "sha1" : "00512328ab7a548fbb8d5c88bac113b7bb8b42a1",
      "md5" : "1282d1319b7e972ea0279670ab5d95ed"
    } ]
  }, {
    "name" : "sourcesElements",
    "attributes" : {
      "org.gradle.category" : "documentation",
      "org.gradle.dependency.bundling" : "external",
      "org.gradle.docstype" : "sources",
      "org.gradle.usage" : "java-runtime"
    },
    "files" : [ {
      "name" : "flabel-eae3c2dc59.jar",
      "url" : "flabel-eae3c2dc59.jar",
      "size" : 20633,
      "sha512" : "b7fda7c51f541034b539baa8fed6d9c7ae444c8393ad49db60b5efe85b7f2fc80e560f984f602684cc609be57cf29b59d69bb4bfe00593140d13074a51537698",
      "sha256" : "23e7835cbb5c13daa8c7a67b3e7671d0baca3c99168f029b1984472f516327de",
      "sha1" : "1402af0e7c6f9d1e9d537670103478e65efe05be",
      "md5" : "a47a373b3345d6a0779384e8789b2779"
    } ]
  } ]
}